language: php

matrix:
  include:
    - php: 5.6
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=true
    - php: 7.0
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
    - php: 7.1
      env: COLLECT_COVERAGE=true VALIDATE_CODING_STYLE=false
    - php: hhvm
      env: COLLECT_COVERAGE=false VALIDATE_CODING_STYLE=false
  allow_failures:
    - php: hhvm
  fast_finish: true

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
 - if [ "$COLLECT_COVERAGE" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
 - if [ "$VALIDATE_CODING_STYLE" == "true" ]; then composer phpcs fi

notifications:
  email: false
